language: python

python:
 - 2.7

install:
 - pip install codecov
 - pip install pyactor
 - pip install coverage


script:
 - python -m SimpleHTTPServer &
 - ptyhon coverage run tests.py

after_success:
 - codecov -t b7db6994-c65b-48ba-84ab-56937e9260b7
